apiVersion: v1
kind: Service
metadata:
  labels:
    service: visit-api
  name: visit-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30005
  selector:
    service: visit-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: visit-api
  name: visit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: visit-api
  template:
    metadata:
      labels:
        service: visit-api
    spec:
      containers:
      - image: chandc/visitservice-api:latest
        name: visit-api
        imagePullPolicy: Always
      restartPolicy: Always
