# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import person_pb2 as person__pb2


class PersonRequestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PersonLookup = channel.unary_stream(
                '/PersonRequest/PersonLookup',
                request_serializer=person__pb2.Empty.SerializeToString,
                response_deserializer=person__pb2.Person.FromString,
                )


class PersonRequestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PersonLookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonRequestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PersonLookup': grpc.unary_stream_rpc_method_handler(
                    servicer.PersonLookup,
                    request_deserializer=person__pb2.Empty.FromString,
                    response_serializer=person__pb2.Person.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PersonRequest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PersonRequest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PersonLookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PersonRequest/PersonLookup',
            person__pb2.Empty.SerializeToString,
            person__pb2.Person.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
